#! /usr/bin/python

# @file
#  This file is part of PUMGen
#
#  For conditions of distribution and use, please see the copyright
#  notice in the file 'COPYING' at the root directory of this package
#  and the copyright notice at https://github.com/SeisSol/PUMGen
#
# @copyright 2017 Technical University of Munich
# @author Sebastian Rettenberger <sebastian.rettenberger@tum.de>
#

Import('env')

env.sourceFiles.extend([
    env.Object('GambitReader.cpp'),
    env.Object('FidapReader.cpp')])

Export('env')