# SPDX-FileCopyrightText: 2025 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

---

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-merge-conflict
        name: '[GENERIC] merge conflict check'
    -   id: check-symlinks
        name: '[GENERIC] symlink check'
    -   id: destroyed-symlinks
        name: '[GENERIC] detect broken symlinks'
    -   id: detect-private-key
        name: '[GENERIC] detect private keys uploaded by accident'
    -   id: check-case-conflict
        name: '[GENERIC] detect OS file naming case conflicts'
    -   id: check-executables-have-shebangs
        name: '[GENERIC] check for shebangs in executable files'
    #-   id: check-illegal-windows-names
    #    name: '[GENERIC] detect illegal Windows file names'
    -   id: check-json
        name: '[JSON] check'
    #-   id: check-xml
    #    name: '[XML] check'

-   repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
    -   id: markdownlint-cli2
        name: '[MARKDOWN] lint'

#-   repo: https://github.com/fsfe/reuse-tool
#    rev: v5.1.1
#    hooks:
#    -   id: reuse
#        name: '[GENERIC] REUSE compatibiltiy'

-   repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: 'v1.0.0'
    hooks:
    -   id: sphinx-lint
        name: '[SPHINX/RST] sphinx lint'

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v21.1.0'
    hooks:
    -   id: clang-format
        name: '[C++] clang-format'

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
        name: '[GENERIC] newline eof'
    -   id: trailing-whitespace
        name: '[GENERIC] remove trailing whitespace'
