sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

language: cpp

compiler: gcc

dist: bionic

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq g++-5 openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-100 libhdf5-openmpi-dev libnetcdf-dev
 - cd ..
# Download simmetrix libraries 
# check license
#build pumi
 - git clone https://github.com/SCOREC/core.git
 - mkdir pumi
 - mkdir core/build
 - cd core/build
 - cmake .. -DCMAKE_C_COMPILER="`which mpicc`" -DCMAKE_CXX_COMPILER="`which mpiCC`" -DCMAKE_C_FLAGS="-O2 -g -Wall" -DCMAKE_CXX_FLAGS="-O2 -g -Wall" -DCMAKE_INSTALL_PREFIX=../../pumi 
 - make -j2 && make install
 - make -j2 && make install
#Go back to PUMGen
 - cd ../../PUMGen
 - mkdir build && cd build

script:
 - CC=mpicc CXX=mpiCC cmake .. -DCMAKE_PREFIX_PATH=../pumi && make -j2 
