#! /usr/bin/python

# @file
#  This file is part of PUMGen
#
#  For conditions of distribution and use, please see the copyright
#  notice in the file 'COPYING' at the root directory of this package
#  and the copyright notice at https://github.com/SeisSol/PUMGen
#
# @copyright 2017 Technical University of Munich
# @author Sebastian Rettenberger <sebastian.rettenberger@tum.de>
#

Import('env')

env.sourceFiles = [env.Object('pumgen.cpp')]

for dir in ['input', 'meshreader']:
	Export('env')
	SConscript(dir+'/SConscript', variant_dir='#/'+env['buildDir']+'/src/'+dir, src_dir='#/src/'+dir, duplicate=0)
	Import('env')

Export('env')