#! /usr/bin/python

# @file
#  This file is part of PUMGen
#
#  For conditions of distribution and use, please see the copyright
#  notice in the file 'COPYING' at the root directory of this package
#  and the copyright notice at https://github.com/SeisSol/PUMGen
#
# @copyright 2017 Technical University of Munich
# @author Sebastian Rettenberger <sebastian.rettenberger@tum.de>
#

Import('env')

env.sourceFiles.append(env.Object('ParallelVertexFilter.cpp'))
env.sourceFiles.append(env.Object('AnalysisAttributes.cpp'))
env.sourceFiles.append(env.Object('MeshAttributes.cpp'))
env.sourceFiles.append(env.Object('split.cpp'))
env.sourceFiles.append(env.Object('../../../submodules/tinyxml2/tinyxml2.cpp'))

if env['use_netcdf']:
	env.sourceFiles.append(env.Object('NetCDFPartition.cpp'))

if env['use_simmodsuite']:
	env.sourceFiles.append(env.Object('SimModSuite.cpp'))

Export('env')
