# SPDX-FileCopyrightText: 2022 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause

name: CMake

on: [push]

jobs:
  # Build pumgen in Release and Debug version
  build-pumgen:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq g++ openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-dev libnetcdf-dev

      - name: Configure PUMGen
        working-directory: ${{ github.workspace }}
        run: |
          git submodule update --init --recursive
          mkdir build_${{ matrix.build_type}} && cd build_${{ matrix.build_type}}
          cmake .. -DCMAKE_PREFIX_PATH=${{ runner.workspace }}/opt -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        working-directory: ${{ github.workspace }}/build_${{ matrix.build_type }}
        run: cmake --build .

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: apt-get
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get -y install python3.13

      - uses: pre-commit/action@v3.0.1
